name: Combined SCA Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Run OWASP Dependency Check
  sca_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.1.1/dependency-check-7.1.1-release.zip
          unzip dependency-check-7.1.1-release.zip -d dependency-check
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh

      - name: Run OWASP Dependency Check
        run: |
          mkdir -p security-reports  # Create directory for reports
          dependency-check/dependency-check/bin/dependency-check.sh --project "My Project SCA" \
          --scan $(pwd) --format "ALL" --out $(pwd)/security-reports/dependency-check-report

      - name: Upload Dependency Check Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: security-reports/dependency-check-report

  # Job 2: Run Snyk Scan
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        run: |
          mkdir -p security-reports  # Ensure reports directory exists
          snyk test --all-projects --json-file-output=security-reports/snyk-sca-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-sca-report
          path: security-reports/snyk-sca-report.json

  # Job 3: Combine Both Reports
  combine_reports:
    runs-on: ubuntu-latest
    needs: [sca_scan, snyk_scan]  # Wait for both SCA and Snyk jobs to complete

    steps:
      - name: Download Dependency Check Report
        uses: actions/download-artifact@v3
        with:
          name: dependency-check-report
          path: security-reports

      - name: Download Snyk Report
        uses: actions/download-artifact@v3
        with:
          name: snyk-sca-report
          path: security-reports

      - name: Generate Consolidated Report
        run: |
          # Create a consolidated report file
          echo "### Consolidated SCA Security Report" > security-reports/consolidated-report.md
          
          # Add Dependency Check Report
          if [[ -f "security-reports/dependency-check-report/dependency-check-report.html" ]]; then
            echo "#### OWASP Dependency Check Report" >> security-reports/consolidated-report.md
            cat security-reports/dependency-check-report/dependency-check-report.html >> security-reports/consolidated-report.md
          else
            echo "Dependency Check report not found!" >> security-reports/consolidated-report.md
          fi
          
          # Add Snyk SCA Report
          if [[ -f "security-reports/snyk-sca-report.json" ]]; then
            echo "#### Snyk SCA Report" >> security-reports/consolidated-report.md
            cat security-reports/snyk-sca-report.json >> security-reports/consolidated-report.md
          else
            echo "Snyk SCA report not found!" >> security-reports/consolidated-report.md
          fi

      - name: Upload Consolidated Report
        uses: actions/upload-artifact@v3
        with:
          name: consolidated-report
          path: security-reports/consolidated-report.md
