name: Combined SCA Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Run OWASP Dependency Check
  sca_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.1.1/dependency-check-7.1.1-release.zip
          unzip dependency-check-7.1.1-release.zip -d dependency-check
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh

      - name: Run OWASP Dependency Check
        run: |
          mkdir -p security-reports  # Create directory for reports
          dependency-check/dependency-check/bin/dependency-check.sh --project "My Project SCA" \
          --scan $(pwd) --format "ALL" --out $(pwd)/security-reports/dependency-check-report

      - name: Upload Dependency Check Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: security-reports/dependency-check-report.html

  # Job 2: Run Snyk Scan
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt     

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        run: |
          mkdir -p security-reports  # Ensure reports directory exists
          DEBUG=*snyk* snyk test --file=requirements.txt --json-file-output=security-reports/snyk-sca-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

     # Generate HTML from Snyk JSON Report using a simple converter
      - name: Convert Snyk JSON Report to HTML
        run: |
          echo "<html><body><h1>Snyk SCA Report</h1><pre>" > security-reports/snyk-sca-report.html
          cat security-reports/snyk-sca-report.json | jq . >> security-reports/snyk-sca-report.html
          echo "</pre></body></html>" >> security-reports/snyk-sca-report.html

      - name: Upload Snyk HTML Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-sca-report
          path: security-reports/snyk-sca-report.html

  # Job 3: Combine Both Reports
  combine_reports:
    runs-on: ubuntu-latest
    needs: [sca_scan, snyk_scan]  # Wait for both SCA and Snyk jobs to complete

    steps:
      - name: Download Dependency Check Report
        uses: actions/download-artifact@v3
        with:
          name: dependency-check-report
          path: security-reports

      - name: Download Snyk Report
        uses: actions/download-artifact@v3
        with:
          name: snyk-sca-report
          path: security-reports

       # Install pandoc for Markdown to HTML conversion
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc
    

       # Combine the Dependency Check and Snyk HTML reports into one HTML file
      - name: Combine Reports into Consolidated HTML
        run: |
          pandoc security-reports/dependency-check-report.html security-reports/snyk-sca-report.html \
          -s -o security-reports/consolidated-report.html

      - name: Upload Consolidated Report
        uses: actions/upload-artifact@v3
        with:
          name: consolidated-report
          path: security-reports/consolidated-report.html
