name: Combined SCA Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sca_scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Download and Set up OWASP Dependency Check
      - name: Download OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.1.1/dependency-check-7.1.1-release.zip
          unzip dependency-check-7.1.1-release.zip -d dependency-check
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh

      # Step 3: Run OWASP Dependency Check
      - name: Run OWASP Dependency Check
        run: |
          mkdir -p security-reports  # Create a directory for reports
          dependency-check/dependency-check/bin/dependency-check.sh --project "My Project SCA" \
          --scan $(pwd) --format "ALL" --out $(pwd)/security-reports/dependency-check-report

      # Step 4: Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Step 5: Run Snyk Security Scan
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --all-projects --json-file-output=security-reports/snyk-sca-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Step 6: Generate Consolidated Report
      - name: Generate Consolidated Report
        run: |
          # Create consolidated report file
          echo "### Consolidated SCA Security Report" > security-reports/consolidated-report.md
          
          # Add Dependency Check Report
          if [[ -f "security-reports/dependency-check-report/dependency-check-report.html" ]]; then
            echo "#### OWASP Dependency Check Report" >> security-reports/consolidated-report.md
            cat security-reports/dependency-check-report/dependency-check-report.html >> security-reports/consolidated-report.md
          else
            echo "Dependency Check report not found!" >> security-reports/consolidated-report.md
          fi
          
          # Add Snyk SCA Report
          if [[ -f "security-reports/snyk-sca-report.json" ]]; then
            echo "#### Snyk SCA Report" >> security-reports/consolidated-report.md
            cat security-reports/snyk-sca-report.json >> security-reports/consolidated-report.md
          else
            echo "Snyk SCA report not found!" >> security-reports/consolidated-report.md
          fi

      # Step 7: Upload Security Reports as Artifacts
      - name: Upload Security Reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: security-reports/

      # Optional Step 8: Fail the workflow if vulnerabilities are found
      - name: Check for Vulnerabilities
        run: |
          if grep -q "VULNERABILITY FOUND" security-reports/dependency-check-report/dependency-check-report.xml || \
             grep -q "\"vulnerabilities\":[]" security-reports/snyk-sca-report.json; then
            echo "Vulnerabilities found in dependencies."
            exit 1
          else
            echo "No vulnerabilities found."
          fi
