name: Combined SCA Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Run OWASP Dependency Check
  sca_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.1.1/dependency-check-7.1.1-release.zip
          unzip dependency-check-7.1.1-release.zip -d dependency-check
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh

      - name: Run OWASP Dependency Check
        run: |
          mkdir -p security-reports  # Create directory for reports
          dependency-check/dependency-check/bin/dependency-check.sh --project "My Project SCA" \
          --scan $(pwd) --format "ALL" --out $(pwd)/security-reports/dependency-check-report

      - name: Upload Dependency Check Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: security-reports/dependency-check-report

  # Job 2: Run Snyk Scan
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Install snyk-to-html
        run: npm install -g snyk-to-html  # Install snyk-to-html

      - name: Run Snyk to check for vulnerabilities
        run: |
          mkdir -p security-reports  # Ensure reports directory exists
          snyk test --file=requirements.txt --json | snyk-to-html -o security-reports/snyk-sca-report.html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-sca-report
          path: security-reports/snyk-sca-report.html

  # Job 3: Combine Both Reports
  combine_reports:
    runs-on: ubuntu-latest
    needs: [sca_scan, snyk_scan]

    steps:
      - name: Download Dependency Check Report
        uses: actions/download-artifact@v3
        with:
          name: dependency-check-report
          path: security-reports

      - name: Download Snyk Report
        uses: actions/download-artifact@v3
        with:
          name: snyk-sca-report
          path: security-reports

      - name: Generate Consolidated HTML Report
        run: |
          echo "<html><body><h1>Consolidated SCA Security Report</h1>" > security-reports/consolidated-report.html
          
          # Add Dependency Check HTML Report if available
          if [[ -f "security-reports/dependency-check-report/dependency-check-report.html" ]]; then
            echo "<h2>OWASP Dependency Check Report</h2>" >> security-reports/consolidated-report.html
            cat security-reports/dependency-check-report/dependency-check-report.html >> security-reports/consolidated-report.html
          else
            echo "<p>Dependency Check report not found!</p>" >> security-reports/consolidated-report.html
          fi
          
          # Add Snyk HTML Report if available
          if [[ -f "security-reports/snyk-sca-report.html" ]]; then
            echo "<h2>Snyk SCA Report</h2>" >> security-reports/consolidated-report.html
            cat security-reports/snyk-sca-report.html >> security-reports/consolidated-report.html
          else
            echo "<p>Snyk SCA report not found!</p>" >> security-reports/consolidated-report.html
          fi

          echo "</body></html>" >> security-reports/consolidated-report.html

      - name: Upload Consolidated HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: consolidated-report
          path: security-reports/consolidated-report.html
