jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create Docker Network
        run: docker network create zap-network

      - name: Build Docker Image
        run: docker build -t my-python-app .

      - name: Start Application
        run: docker run -d --name my-app --network zap-network -p 5000:5000 my-python-app

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://my-app:5000"
          cmd_options: "-r zap_report.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker run --rm --network zap-network ghcr.io/zaproxy/zaproxy:weekly zap-baseline.py -t http://my-app:5000 -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html

      - name: Stop Application
        run: docker stop my-app && docker rm my-app

      - name: Remove Docker Network
        run: docker network rm zap-network
