name: OWASP ZAP Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Start the Application (adjust as needed)
      - name: Start Application
        run: |
          docker run -d --name my-app -p 8080:8080 my-app-image  # Replace 'my-app-image' with your actual Docker image name

      # Run OWASP ZAP Baseline Scan
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:8080"  # Replace with your app's URL and port
          cmd_options: "-r zap_report.html"  # Generates an HTML report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload ZAP Report as Artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html

      # Stop and Remove the Application Container
      - name: Stop Application
        run: docker stop my-app && docker rm my-app
