name: OWASP ZAP Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Build the Docker Image from the Dockerfile
      - name: Build Docker Image
        run: docker build -t my-python-app .

      # Step 3: Start the Application
      - name: Start Application
        run: docker run -d --name my-app -p 8080:8080 my-python-app

      # Step 4: Run OWASP ZAP Baseline Scan
      - name: OWASP ZAP Baseline Scan
        run: |
          docker run --rm \
            --network="host" \
            -v $(pwd):/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:weekly \
            zap-baseline.py -t http://localhost:8080 -r zap_report.html

      # Step 5: Upload ZAP Report as Artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html

      # Step 6: Stop and Remove the Application Container
      - name: Stop Application
        run: docker stop my-app && docker rm my-app
