name: OWASP ZAP Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Start the Application with Docker Compose
      - name: Start Application
        run: docker-compose up -d  # Adjust with your actual docker-compose file and service configuration

      # Run OWASP ZAP Baseline Scan
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:8080"  # Replace with your actual app URL
          cmd_options: "-r zap_report.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload ZAP Report
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html

