name: OWASP ZAP Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-python-app .

      - name: Start Application
        run: docker run -d --name my-app -p 8080:8080 my-python-app

      - name: Verify Application is Running
        run: |
          sleep 5
          curl -I http://localhost:8080 || (docker logs my-app && exit 1)

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:8080"
          cmd_options: "-r zap_report.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html

      - name: Stop Application
        run: docker stop my-app && docker rm my-app
