name: OWASP ZAP Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Start the Application (replace this with your actual application start command)
      - name: Start Application
        run: |
          docker-compose up -d  # Replace with the command to start your app

      # Run OWASP ZAP Baseline Scan
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:8080"  # Replace with your app's actual URL
          cmd_options: "-r zap_report.html"  # Generate an HTML report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload ZAP Report as Artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html
