name: SCA Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sca_scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Download and Set up OWASP Dependency Check
      - name: Download OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.1.1/dependency-check-7.1.1-release.zip
          unzip dependency-check-7.1.1-release.zip -d dependency-check
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh  # Corrected path

      # Step 3: Run OWASP Dependency Check
      - name: Run OWASP Dependency Check
        run: |
          dependency-check/dependency-check/bin/dependency-check.sh --project "My Project SCA" \
          --scan $(pwd) --format "ALL" --out $(pwd)/dependency-check-report

      # Step 4: Upload Dependency Check Report as Artifact
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report/

      # Step 5: Optional - Fail the workflow if vulnerabilities are found
      - name: Check for Vulnerabilities
        run: |
          if grep -q "VULNERABILITY FOUND" dependency-check-report/dependency-check-report.xml; then
            echo "Vulnerabilities found in dependencies."
            exit 1
          else
            echo "No vulnerabilities found."
          fi
