name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the Python version your project requires

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Snyk CLI
        run: npm install -g snyk snyk-to-html

      - name: Run Snyk to generate JSON report
        run: snyk test --file=requirements.txt --json-file-output=snyk-sca-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Generate HTML report from JSON
        run: snyk-to-html -i snyk-sca-report.json -o snyk-sca-report.html

      - name: Upload Snyk HTML Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-sca-report
          path: snyk-sca-report.html
