name: Combined Security Scans

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: SonarQube SAST Scan
  sonarcloud_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17  # Ensuring Java 17 is active

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip
          unzip sonar-scanner.zip -d $HOME/sonar-scanner
          echo "$HOME/sonar-scanner/sonar-scanner-4.5.0.2216-linux/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: /opt/hostedtoolcache/jdk/17.0.12/x64  # Ensure correct Java path
        run: |
          $HOME/sonar-scanner/sonar-scanner-4.5.0.2216-linux/bin/sonar-scanner \
            -Dsonar.projectKey=projectdevsecops \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.report.export.path=security-reports/sonar_report.html  # Specifying report output

      - name: Upload SonarQube Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sonar_report
          path: security-reports/sonar_report.html
