name: SonarCloud Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install html-sonar-report
        run: |
          npm install -g html-sonar-report

      - name: Generate HTML Report
        run: |
          html-sonar-report --token ${{ secrets.SONAR_TOKEN }} --url https://sonarcloud.io --component <your_project_key> --output sonar-report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: SonarCloud HTML Report
          path: sonar-report.html
