name: Security Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: SonarQube Scan with Docker
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="https://sonarcloud.io" \
            -e SONAR_LOGIN="${{ secrets.SONAR_TOKEN }}" \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=projectdevsecops \
            -Dsonar.sources=.

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --file=requirements.txt --json > snyk_report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk report
        uses: actions/upload-artifact@v3
        with:
          name: snyk_report
          path: snyk_report.json

      - name: Upload SonarQube report
        uses: actions/upload-artifact@v3
        with:
          name: sonarqube_report
          path: .scannerwork/report-task.txt
