name: Security Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17  # Use the required Java version for SonarQube

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Insall SonaScanner
        run: |
          curl -sSlo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip
          unzip sonar-scanner.zip -d $HOME
          echo "$HOME/sonar-scanner-4.5.0.2216-linux/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV  

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64  
        run: |
          sonar-scanner \
            -Dsonar.projectKey=projectdevsecops \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        continue-on-error: true  # Optionally continue if SonarQube scan fails

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --file=requirements.txt --json > snyk_report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk report
        uses: actions/upload-artifact@v3
        with:
          name: snyk_report
          path: snyk_report.json

      - name: Upload SonarQube report
        uses: actions/upload-artifact@v3
        with:
          name: sonarqube_report
          path: .scannerwork/report-task.txt  # Default location for SonarQube report
