name: SonarCloud Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Generate HTML Report
        if: success()
        run: |
          curl -L https://github.com/mkdocs/sonar-report-converter/releases/latest/download/sonar-report-converter.jar -o sonar-report-converter.jar
          java -jar sonar-report-converter.jar -i .scannerwork/report-task.txt -o sonar-report.html

      - name: Upload HTML Report
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: SonarCloud HTML Report
          path: sonar-report.html
