name: SonarCloud Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Export SonarCloud Report to JSON
        run: |
          mkdir -p /tmp/sonar
          curl -X GET -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/issues/search?componentKeys=mekaizen_projectdevsecops&types=BUG,VULNERABILITY,CODE_SMELL&ps=500" > /tmp/sonar/sonar-report.json

      - name: Convert JSON to HTML
        run: |
          echo "<html><body><h2>SonarCloud Issues Report</h2><ul>" > /tmp/sonar/sonar-report.html
          jq -r '.issues[] | "<li>\(.message) - Severity: \(.severity)</li>"' /tmp/sonar/sonar-report.json >> /tmp/sonar/sonar-report.html
          echo "</ul></body></html>" >> /tmp/sonar/sonar-report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: SonarCloud HTML Report
          path: /tmp/sonar/sonar-report.html
