name: SonarCloud Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Export SonarCloud Report to JSON
        run: |
          mkdir -p security-reports
          curl -X GET -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/issues/search?componentKeys=mekaizen_projectdevsecops&types=BUG,VULNERABILITY,CODE_SMELL&ps=500" > security-reports/sonar-report.json
          if ! jq empty security-reports/sonar-report.json > /dev/null 2>&1; then
            echo "Error: Received invalid JSON from SonarCloud API"
            cat security-reports/sonar-report.json
            exit 1
          fi

      - name: Convert JSON to HTML with Chart
        run: |
          {
            echo "<html><head><style>"
            echo "body { font-family: Arial, sans-serif; margin: 20px; }"
            echo "h2 { color: #4CAF50; }"
            echo "h3 { margin-top: 20px; }"
            echo "ul { list-style-type: none; padding: 0; }"
            echo "li { margin: 10px 0; padding: 8px; border: 1px solid #ddd; border-radius: 4px; }"
            echo ".severity-HIGH { color: #ff4d4d; font-weight: bold; }"
            echo ".severity-MEDIUM { color: #0066cc; }"
            echo ".severity-LOW { color: #666666; }"
            echo "</style><script src='https://cdn.jsdelivr.net/npm/chart.js'></script></head><body>"
            echo "<h2>SonarCloud Issues Report</h2>"
          } > security-reports/sonar-report.html

      - name: Upload SonarCloud HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: sonar_report
          path: security-reports/sonar-report.html

  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:8080"
          cmd_options: "-r security-reports/zap_report.html -J security-reports/zap_out.json -w security-reports/zap_report.md"
          docker_name: "ghcr.io/zaproxy/zaproxy:weekly"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Reports as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zap_reports
          path: security-reports

  sca_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run OWASP Dependency Check
        run: |
          mkdir -p security-reports
          dependency-check/dependency-check/bin/dependency-check.sh --project "My Project SCA" \
          --scan $(pwd) --format "HTML" --out security-reports/dependency-check-report.html

      - name: Upload Dependency Check Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependency_check_report
          path: security-reports/dependency-check-report.html

  combine_reports:
    runs-on: ubuntu-latest
    needs: [sonarcloud_scan, zap_scan, sca_scan]
    steps:
      - name: Download SonarQube Report
        uses: actions/download-artifact@v3
        with:
          name: sonar_report
          path: security-reports

      - name: Download ZAP Report
        uses: actions/download-artifact@v3
        with:
          name: zap_reports
          path: security-reports

      - name: Download Dependency Check Report
        uses: actions/download-artifact@v3
        with:
          name: dependency_check_report
          path: security-reports

      - name: Generate Consolidated HTML Report
        run: |
          echo "<html><head><style>body { font-family: Arial, sans-serif; } h1, h2 { color: #4CAF50; }</style></head><body><h1>Consolidated Security Report</h1>" > security-reports/consolidated-report.html

          # Add SonarQube HTML Report if available
          if [[ -f "security-reports/sonar-report.html" ]]; then
            echo "<h2>SonarQube SAST Report</h2>" >> security-reports/consolidated-report.html
            cat security-reports/sonar-report.html >> security-reports/consolidated-report.html
          else
            echo "<p>SonarQube report not found!</p>" >> security-reports/consolidated-report.html
          fi

          # Add ZAP HTML Report if available
          if [[ -f "security-reports/zap_report.html" ]]; then
            echo "<h2>OWASP ZAP DAST Report</h2>" >> security-reports/consolidated-report.html
            cat security-reports/zap_report.html >> security-reports/consolidated-report.html
          else
            echo "<p>ZAP report not found!</p>" >> security-reports/consolidated-report.html
          fi

          # Add Dependency Check HTML Report if available
          if [[ -f "security-reports/dependency-check-report.html" ]]; then
            echo "<h2>OWASP Dependency Check SCA Report</h2>" >> security-reports/consolidated-report.html
            cat security-reports/dependency-check-report.html >> security-reports/consolidated-report.html
          else
            echo "<p>Dependency Check report not found!</p>" >> security-reports/consolidated-report.html
          fi

          echo "</body></html>" >> security-reports/consolidated-report.html

      - name: Upload Consolidated HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: consolidated-report
          path: security-reports/consolidated-report.html
