name: SonarCloud Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Export SonarCloud Report to JSON
        run: |
          mkdir -p /tmp/sonar
          curl -X GET -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/issues/search?componentKeys=mekaizen_projectdevsecops&types=BUG,VULNERABILITY,CODE_SMELL&ps=500" > /tmp/sonar/sonar-report.json
          # Check if JSON is valid
          if ! jq empty /tmp/sonar/sonar-report.json > /dev/null 2>&1; then
            echo "Error: Received invalid JSON from SonarCloud API"
            cat /tmp/sonar/sonar-report.json
            exit 1
          fi

      - name: Convert JSON to HTML with Chart
        run: |
          # Create HTML report with categorization and chart
          echo "<html><head><style>
          body { font-family: Arial, sans-serif; margin: 20px; }
          h2 { color: #4CAF50; }
          h3 { margin-top: 20px; }
          ul { list-style-type: none; padding: 0; }
          li { margin: 10px 0; padding: 8px; border: 1px solid #ddd; border-radius: 4px; }
          .severity-HIGH { color: #ff4d4d; font-weight: bold; }
          .severity-MEDIUM { color: #0066cc; } /* Changed to blue for better readability */
          .severity-LOW { color: #666666; }
          </style><script src='https://cdn.jsdelivr.net/npm/chart.js'></script></head><body>" > /tmp/sonar/sonar-report.html
          
          echo "<h2>SonarCloud Issues Report</h2>" >> /tmp/sonar/sonar-report.html
          
          # Initialize JavaScript object for chart data
          echo "<script>const issueData = {HIGH: 0, MEDIUM: 0, LOW: 0};</script>" >> /tmp/sonar/sonar-report.html
          
          # Categorize issues by severity
          echo "<h3>High Severity Issues</h3><ul>" >> /tmp/sonar/sonar-report.html
          jq -r '.issues[] | select(.severity == "BLOCKER" or .severity == "CRITICAL") | "<li class=\"severity-HIGH\">\(.message) - Severity: HIGH</li>"' /tmp/sonar/sonar-report.json >> /tmp/sonar/sonar-report.html
          echo "</ul><h3>Medium Severity Issues</h3><ul>" >> /tmp/sonar/sonar-report.html
          jq -r '.issues[] | select(.severity == "MAJOR") | "<li class=\"severity-MEDIUM\">\(.message) - Severity: MEDIUM</li>"' /tmp/sonar/sonar-report.json >> /tmp/sonar/sonar-report.html
          echo "</ul><h3>Low Severity Issues</h3><ul>" >> /tmp/sonar/sonar-report.html
          jq -r '.issues[] | select(.severity == "MINOR") | "<li class=\"severity-LOW\">\(.message) - Severity: LOW</li>"' /tmp/sonar/sonar-report.json >> /tmp/sonar/sonar-report.html
          echo "</ul>" >> /tmp/sonar/sonar-report.html
          
          # JavaScript Chart
          echo "<h3>Severity Distribution</h3><canvas id='severityChart' width='400' height='400'></canvas>
          <script>
          const data = {
            labels: ['High', 'Medium', 'Low'],
            datasets: [{
              label: 'Issue Severity Distribution',
              data: [issueData.HIGH, issueData.MEDIUM, issueData.LOW],
              backgroundColor: ['#ff4d4d', '#0066cc', '#666666'], /* Updated color for Medium */
              hoverOffset: 4
            }]
          };
          const config = {
            type: 'pie',
            data: data,
          };
          new Chart(document.getElementById('severityChart'), config);
          </script>" >> /tmp/sonar/sonar-report.html
          
          echo "</body></html>" >> /tmp/sonar/sonar-report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: SonarCloud HTML Report
          path: /tmp/sonar/sonar-report.html
