name: OWASP ZAP Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Build the Docker Image from the Dockerfile
      - name: Build Docker Image
        run: docker build -t my-python-app .

      # Step 3: Start the Application
      - name: Start Application
        run: docker run -d --name my-app -p 8080:8080 my-python-app

      # Step 4: Create Report Directory
      - name: Create Report Directory
        run: mkdir -p zap-reports && chmod 777 zap-reports

      # Step 5: Run OWASP ZAP Baseline Scan
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:8080"  # Ensure this matches your app's port
          cmd_options: "-r zap-reports/zap_report.html -J zap-reports/zap_out.json -w zap-reports/zap_report.md"  # Output to zap-reports directory
          docker_name: "ghcr.io/zaproxy/zaproxy:weekly"  # Use the weekly image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Upload ZAP Reports as Artifacts
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap_reports
          path: zap-reports

      # Step 7: Stop and Remove the Application Containers
      - name: Stop Application
        run: docker stop my-app && docker rm my-app
